# -*- coding: utf-8 -*-
"""detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8aKthm5zhEmB_LnNw-VRjliEukYUzN8
"""

# -*- coding: utf-8 -*-
from flask import Flask, request, jsonify
from sentence_transformers import SentenceTransformer
import numpy as np

app = Flask(__name__)

# -------------------------------
# 1️⃣ إعداد الأعراض
# -------------------------------
SYMPTOMS = [
    {"key": "abdominal_pain", "text": "ألم في البطن"},
    {"key": "headache", "text": "صداع"},
    {"key": "nausea", "text": "غثيان"},
    {"key": "dry_mouth", "text": "جفاف الفم"},
    {"key": "fever", "text": "حمى"},
    {"key": "cough", "text": "سعال"},
    {"key": "fatigue", "text": "إرهاق"},
    {"key": "dizziness", "text": "دوخة"},
]

# -------------------------------
# 2️⃣ تحميل نموذج الـ Embeddings
# -------------------------------
model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v2')
symptom_texts = [s["text"] for s in SYMPTOMS]
symptom_embeddings = model.encode(symptom_texts)

# -------------------------------
# 3️⃣ دالة اكتشاف الأعراض
# -------------------------------
def detect_symptoms_embedding(user_text, top_k=5, threshold=0.2):
    user_emb = model.encode([user_text])[0]
    similarities = [np.dot(user_emb, emb) / (np.linalg.norm(user_emb)*np.linalg.norm(emb)) for emb in symptom_embeddings]
    top_indices = np.argsort(similarities)[::-1][:top_k]
    detected = []
    for idx in top_indices:
        if similarities[idx] >= threshold:
            detected.append({
                "key": SYMPTOMS[idx]["key"],
                "text": SYMPTOMS[idx]["text"],
                "similarity": float(similarities[idx])
            })
    return detected

# -------------------------------
# 4️⃣ Endpoint للـ API
# -------------------------------
@app.route("/api/detect", methods=["POST"])
def detect():
    data = request.get_json()
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "No text provided"}), 400

    detected = detect_symptoms_embedding(text)
    return jsonify({"detected": detected})

# -------------------------------
# 5️⃣ تشغيل التطبيق (للتطوير المحلي)
# -------------------------------
if __name__ == "__main__":
    app.run(debug=True)